Repository BamaCharanChhandogi/Diabetes-Prediction, pull requests merged in 2024-07, with the labels that each got.

#125 Added AI Chatbot
  SugarSafe - 2024 Jun 30.bpz
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/FloatBtn.jsx
  client/src/index.css
Labels: gssoc, level3

#99 Feat: Added testimonials
  client/src/components/Home.jsx
  client/src/components/Testimonials/Testimonials.jsx
  client/src/components/Testimonials/testimonials.js
Labels: level1, gssoc

#113 UI-Enhancement
  client/package-lock.json
  client/src/components/Prediction.jsx
Labels: level2, gssoc

#133 Enhanced Readme.md
  client/src/assets/Gssoc Label.png
  readme.md
Labels: level1, gssoc

#138 Added social media icons
  client/package-lock.json
  client/src/components/Footer.jsx
Labels: level1, gssoc

#139 Issue number : #137 Added a suitable logo for the website.
  client/package-lock.json
  client/src/assets/logo_diabetes.png
  client/src/assets/logo_final.png
  client/src/components/Navbar.jsx
Labels: level1, gssoc

#144 Fixed Issue No. #140
  client/package-lock.json
  client/src/components/Home.jsx
  client/src/components/Navbar.jsx
Labels: level2, gssoc

#150 Created Best Pull request_Template
  .github/pull_request_template.md
Labels: level1, gssoc

#151 Feat : Updated readme.md
  readme.md
Labels: level1, gssoc

#152 UI Enhancement of Navbar
  client/src/components/Navbar.jsx
  client/tailwind.config.js
Labels: level1, gssoc
