Repository BamaCharanChhandogi/Diabetes-Prediction, pull requests merged in 2024-06, with the labels that each got.

#56 [Feat]: NavBar should close When Navitem is clicked in mobile devices
  client/src/components/Navbar.jsx
Labels: level1, gssoc

#62 Custom Scrollbar added
  client/src/App.css
  client/src/App.jsx
Labels: level1, gssoc

#36 added socials and quick links
  client/src/components/Footer.jsx
Labels: level1, gssoc

#75 Update CONTRIBUTION.md
  CONTRIBUTION.md
Labels: level1, gssoc

#79 Replace twitter icon with X
  client/src/components/Footer.jsx
Labels: level1, gssoc

#76 Feature Enhancement : Added sorting option in each column
  client/package-lock.json
  client/package.json
  client/src/components/DataInfo.jsx
  server/package-lock.json
Labels: level2, gssoc

#100 [Feat]: Created Issue forms and made the issue options more visually appealing
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_update.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: level1, gssoc

#103 changed footer
  client/src/components/Footer.jsx
Labels: level1, gssoc

#116 Using Deep Learning #57
  Model using deep learning/Diabetes.ipynb
  Model using deep learning/deeplearning.pkl
  Model using deep learning/diabetes.csv
  Model using deep learning/requirements.txt
Labels: gssoc, level3

#124 Corrected 'Back-To-Top' Button
  client/package.json
  client/src/components/FloatBtn.jsx
Labels: level1, gssoc
