Repository BamaCharanChhandogi/Diabetes-Prediction, pull requests merged in 2024-05, with the labels that each got.

#4 Added CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc24, level1

#21 added workflow as per issue #14
  .github/workflows/autocomment-issue.yml
Labels: enhancement, level1, gssoc

#13 Updated Readme file
  readme.md
Labels: level1, gssoc

#32 FIXED Issue #6 : Enhanced Alignment of Footer
  client/src/components/Footer.jsx
Labels: level1, gssoc

#39 feat: added FAQ
  client/src/App.jsx
  client/src/components/FAQ.jsx
  client/src/components/Navbar.jsx
Labels: level1, gssoc

#37 added floating btn
  client/src/App.jsx
  client/src/components/FloatBtn.jsx
Labels: level1, gssoc

#23 added workflow as per issue #16
  .github/workflows/autocomment-pr-merge.yml
Labels: level1, gssoc

#38 Added CONTRIBUTION.md
  CONTRIBUTION.md
Labels: level1, gssoc

#33 FIXED Issue #5 : Added a Contact Us Page
  client/package-lock.json
  client/src/App.jsx
  client/src/assets/contact-form.jpg
  client/src/components/Navbar.jsx
  client/src/components/contact.jsx
Labels: level2, gssoc
